[env:esp32-s3-devkitc-1-n16r8]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

platform_packages = 
    esp32 @ https://github.com/espressif/arduino-esp32.git#3.3.6

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=1
    -DUSE_NIMBLE
    -DCONFIG_BT_NIMBLE_MAX_BONDS=8
    -DCONFIG_BT_NIMBLE_MAX_CCCDS=32

lib_deps =
    https://github.com/esp32beans/ESP32_USB_Host_HID.git
    h2zero/NimBLE-Arduino @ ^1.4.1
    adafruit/Adafruit NeoPixel @ ^1.12.0

lib_ldf_mode = deep

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
